# Generated by Django 5.1.3 on 2024-12-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_cpm', models.CharField(max_length=100)),
                ('investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('investment_date', models.DateTimeField()),
            ],
        ),
    ]
